package com.duluthtechnologies.ocpi.model.v211;

public enum Facility {

	HOTEL, RESTAURANT, CAFE, MALL, SUPERMARKET, SPORT, RECREATION_AREA, NATURE, MUSEUM, BUS_STOP, TAXI_STAND,
	TRAIN_STATION, AIRPORT, CARPOOL_PARKING, FUEL_STATION, WIFI

}
