ocpi:
  ocpi-api:
    externalUrl: localhost:8080
  persistence:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/ocpi
    username: test
    password: test
    encryptionPassword: test    